runs:
  steps:
    - name: Checkout capsule
      uses: actions/checkout@v2
      with:
        repository: vegaprotocol/vegacapsule
        ref: main
        token: ${{ secrets.VEGA_CI_BOT_GITHUB_TOKEN }}
        path: './capsule'

    - name: Build capsule
      run: go install
      working-directory: capsule

    - name: Login to docker
      run: echo -n ${{ secrets.VEGA_CI_BOT_GITHUB_TOKEN }} | docker login https://ghcr.io -u vega-ci-bot --password-stdin

    - name: Start nomad
      run: vegacapsule nomad &

    - name: Bootstrap network
      run: vegacapsule network bootstrap --config-path=./frontend-monorepo/vegacapsule/config.hcl --force
