runs:
  using: 'composite'
  steps:
    - name: Start nomad
      shell: bash
      run: vegacapsule nomad &

    - name: Bootstrap network
      shell: bash
      run: vegacapsule network bootstrap --config-path=./frontend-monorepo/vegacapsule/config.hcl --force
