inputs:
  recovery:
    description: 'Recovery phrase'
  passphrase:
    description: 'Wallet password'
runs:
  using: 'composite'
  steps:
    - name: Create passphrase
      shell: bash
      run: echo "${{ inputs.passphrase }}" > ./passphrase

    - name: Create recovery
      shell: bash
      run: echo "${{ inputs.recovery }}" > ./recovery

    - name: Initialize wallet
      shell: bash
      run: vega wallet init -f --home ~/.vegacapsule/testnet/wallet

    - name: Import wallet
      shell: bash
      run: vega wallet import -w UI_Trading_Test --recovery-phrase-file ./recovery -p ./passphrase --home ~/.vegacapsule/testnet/wallet

    - name: Create public key 2
      shell: bash
      run: vega wallet key generate -w UI_Trading_Test -p ./passphrase --home ~/.vegacapsule/testnet/wallet

    - name: Import network
      shell: bash
      run: vega wallet network import --from-url="https://raw.githubusercontent.com/vegaprotocol/networks-internal/main/stagnet3/vegawallet-stagnet3.toml" --force --home ~/.vegacapsule/testnet/wallet

    - name: Start service using stagnet3 network
      shell: bash
      run: vegawallet-dummy service run --network stagnet3 --wallet UI_Trading_Test --passphrase-file ./passphrase --home ~/.vegacapsule/testnet/wallet &
