export default {
  HOME: '/',
  CLAIM: '/claim',
  VALIDATORS: '/validators',
  REWARDS: '/rewards',
  PROPOSALS: '/proposals',
  PROPOSALS_REJECTED: '/proposals/rejected',
  NOT_PERMITTED: '/not-permitted',
  NOT_FOUND: '/not-found',
  CONTRACTS: '/contracts',
  STAKING: '/staking',
  TOKEN: '/token',
  REDEEM: '/token/redeem',
  WITHDRAWALS: '/token/withdraw',
  SUPPLY: '/token/tranches',
  ASSOCIATE: '/token/associate',
};
