export default {
  HOME: '/',
  CLAIM: '/claim',
  VALIDATORS: '/validators',
  REWARDS: '/rewards',
  PROPOSALS: '/proposals',
  NOT_PERMITTED: '/not-permitted',
  NOT_FOUND: '/not-found',
  CONTRACTS: '/contracts',
  STAKING: '/staking',
  TOKEN: '/token',
  VESTING: '/token/vesting',
  WITHDRAWALS: '/token/withdrawals',
  TRANCHES: '/token/tranches',
};
