#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Lint all staged files - this brings more value as pre-commit
# yarn nx format:check

# Test all projects with changes
# yarn nx affected -t test --exclude trading
