inputs:
  all:
    description: 'Install all binaries'
    default: false
  version:
    description: 'Vega version'
  gobin:
    description: 'GOBIN path'
    default: '/home/runner/go/bin'
runs:
  using: 'composite'
  steps:
    - name: Install Vega binaries
      if: ${{ inputs.all }}
      shell: bash
      run: |
        wget 'https://github.com/vegaprotocol/vega/releases/download/${{ inputs.version }}/vega-linux-amd64.zip'
        unzip vega-linux-amd64.zip -d ${{ inputs.gobin }}

    - name: Install date-node binaries
      if: ${{ inputs.all  }}
      shell: bash
      run: |
        wget 'https://github.com/vegaprotocol/vega/releases/download/${{ inputs.version }}/data-node-linux-amd64.zip'
        unzip data-node-linux-amd64.zip -d ${{ inputs.gobin }}

    - name: Install Vega wallet binaries
      shell: bash
      run: |
        wget 'https://github.com/vegaprotocol/vega/releases/download/${{ inputs.version }}/vegawallet-linux-amd64.zip'
        unzip vegawallet-linux-amd64.zip -d ${{ inputs.gobin }}
