name: Cypress tests - PR

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend mono repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Remove package.json & yarn.lock to avoid installing everything
        run: rm package.json yarn.lock

      - name: Install nx
        run: yarn add nx

      # Check SHAs
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}
          set-environment-variables-for-job: true

      # See affected apps
      - name: See affected apps
        run: |
          affected=$(yarn nx print-affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --select=projects)
          projects=""
          if [[ $affected == *"token"* ]]; then projects+='"token-e2e" '; fi
          if [[ $affected == *"trading"* ]]; then projects+='"trading-e2e" '; fi
          if [[ $affected == *"explorer"* ]]; then projects+='"explorer-e2e" '; fi
          projects=${projects%?}
          projects=[${projects// /,}]
          echo PROJECTS=$projects >> $GITHUB_ENV

    outputs:
      projects: ${{ env.PROJECTS }}

  run:
    needs: pr
    uses: ./.github/workflows/cypress-run.yml
    secrets: inherit
    with:
      projects: ${{ needs.pr.outputs.projects }}
      tags: '@smoke @regression'

  # Report single result at the end, to avoid mess with required checks in PR
  result:
    if: ${{ always() }}
    needs: run
    runs-on: ubuntu-latest
    name: Cypress result
    steps:
      - run: |
          result="${{ needs.run.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
