name: Cypress tests -- night run

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  nightly:
    uses: ./.github/workflows/cypress-run.yml
    secrets: inherit
    with:
      projects: '["explorer-e2e"]'
      tags: '@smoke @regression @slow'
