---
name: Check that PR titles match a conventional commit

on:
  pull_request:
    types: [opened, edited]
jobs:
  lint_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        id: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
