---
name: Check that PR titles match a conventional commit

on:
  pull_request:
    types: [opened, edited]
jobs:
  lint_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16
        id: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
      - name: Install @commitlint/cli
        run: npm install -g @commitlint/cli
      - name: Check PR title
        run: echo "${{ github.event.pull_request.title }}" | commitlint
