---
name: Verify PR title

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]
jobs:
  lint_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        id: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - name: Install root dependencies
        run: yarn install
      - name: Check PR title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --config ./commitlint.config-ci.js
