name: Publish containers

# "on":
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"
#       - "v[0-9]+.[0-9]+.[0-9]+-pre[0-9]+"

on:
  pull_request:

jobs:
  master:
    strategy:
      matrix:
        version: ['0.0.5']
        build-platform: ['linux/amd64, linux/arm64']
        app: ['explorer', 'token']
    name: Build the ${{ inputs.image_name }} image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        id: quemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # TODO take version from tag
      - name: Collect images data
        id: tags
        run: |
          echo '::set-output name=current::vegaprotocol/${{ matrix.app }}:v${{ matrix.version }}'
          echo '::set-output name=latest::vegaprotocol/${{ matrix.app }}:latest'

      - name: Echo tags
        run: |
          echo ${{ steps.tags.outputs.latest }}
          echo ${{ steps.tags.outputs.current }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          context: '.'
          file: './Dockerfile.cra'
          build-args: 'APP=${{ matrix.app }}'
          platforms: ${{ matrix.build-platform }}
          tags: ${{ steps.tags.outputs.latest }},${{ steps.tags.outputs.current }}
          push: true
