name: Publish docker containers

'on':
  pull_request:

jobs:
  master:
    strategy:
      fail-fast: false
      # to be replaced by nix: https://github.com/vegaprotocol/frontend-monorepo/blob/develop/tools/ipfs-deploy.js#L106-L108
      matrix:
        app: ${{ fromJson('["explorer"]') }}
    name: Build the ${{ matrix.app }} image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        id: quemu
        uses: docker/setup-qemu-action@v2

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine Docker Image tag
        id: tags
        run: |
          npmVersion=$(cat .nvmrc | head -n 1)
          hash=$(git rev-parse HEAD|cut -b1-8)
          versionTag=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '${hash}' }}
          echo ::set-output name=npmVersion::${npmVersion}
          echo ::set-output name=version::${versionTag}

      - name: Print config
        run: |
          git rev-parse --verify HEAD
          git status
          echo "steps.tags.outputs.version=${{ steps.tags.outputs.version }}"

      - name: Build and export to local Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: dockerfiles/Dockerfile
          build-args: |
            APP=${{ matrix.app }}
            NODE_VERSION=${{ steps.tags.outputs.npmVersion }}
          load: true
          tags: |
            ghcr.io/vegaprotocol/frontend/${{ matrix.app }}:local

      - name: Sanity check docker image
        run: |
          docker run --rm vegaprotocol/${{ matrix.app }}:local cat .env
          docker run --rm vegaprotocol/${{ matrix.app }}:local ls -lah

      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: dockerfiles/Dockerfile
          build-args: |
            APP=${{ matrix.app }}
            NODE_VERSION=${{ steps.tags.outputs.npmVersion }}
          tags: |
            ghcr.io/vegaprotocol/frontend/${{ matrix.app }}:latest
            ghcr.io/vegaprotocol/frontend/${{ matrix.app }}:${{ steps.tags.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
